### ISSUE TITLE
Should also have example of "workspace setup via code" in notebook

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-examples#251]
There's plenty of existing material to draw from.

**Comment by lostmygithubaccount** [comment]
this used to exist - there were a section of `concepts` notebooks overviewing the Python SDK for `Workspace, Dataset, Datastore, Compute Instance, Compute Cluster, Model, Environment, ...`. 

I removed them because:

1. I believe we want to teach as little AML as possible to get users going with their code
2. This type of content should be in docs, not github examples - as a separate note, I think we need a very clear distinction here
3. along those lines, will need it for multiple languages -> should go in docs with a language selector thing
4. don't want to actively advocate setup via notebook in our examples

**Comment by dkmiller** [comment]
At a minimum, this repo uses Python code in `setup.py` to provision a workspace.

It'll change to using the CLI once that's ready.

The 'getting started' tutorial on docs.microsoft.com also nudges users to use the SDK.

Bonus points: "deploy to Azure" button on the repo.
