### ISSUE TITLE
Is it possible to run foundation model inference without deploying to endpoint?

### ISSUE THREAD

**Issue by lucasfbrillet** [Azure/azureml-examples#2749]
### Describe your suggestion

Cannot find any examples doing running inference on the VM without deploying to endpoint previously. Specifically I'm trying to run llama-2 from a python script, I have been able to fetch the model, but not sure how to run inference now.

**Comment by santiagxf** [comment]
Hi @lucasfbrillet, sorry for the delay on the response. I just run across your comment. There are many ways that can be done depending on what's the scenario. You can inference them with vLLM, huggingface, or MLflow. I will assume you want to do a quick test so probably the simplest way is to use `model = mlflow.pyfunc.load_model("<path>")` method from the location where you downloaded the model locally. Our models are MLflow compatible.

Once loaded, then you can use `model.predict()` method.

Please let me know if that helps you out or reopen this issue otherwise.
