### ISSUE TITLE
Relationship with other official Azure ML info?

### ISSUE THREAD

**Issue by kodonnell** [Azure/azureml-examples#291]
This repo (and `azureml-web` and `azureml-template`) look great, but I'm confused - how do these differ from other 'official' repos/docs like `MLOpsPython` or `MachineLearningNotebooks` or just the standard Azure docs/tutorials? There seems like quite a lot of overlap, but also some significant differences.

I don't mind which is 'right' - just that it's easier to focus on one source of truth, if possible, and I want to know which one that is. It'd possibly be good to document this clearly in each repo to avoid future confusion.

**Comment by lostmygithubaccount** [comment]
Acronyms:

- AML: Azure Machine Learning
- GHA: GitHub Actions

This is an excellent question! Apologies about not having this clearly documented. I'll give a short and long answer, and use this issue as the reference documentation for this question. We'll likely publish the answer prominently in the repos/website.

## Short answer

There is a clear and intentional divide between:

- github.com/Azure/MachineLearningNotebooks
- existing assets, including `MLOpsPython` and other accelerator repos (`Recommenders`, `NLP`, `Many Models`)

and:

- github.com/Azure/azureml-exmamples
- github.com/Azure/azureml-template (hopefully more derivative templates soon)
- [github.com/Azure/azureml-web](https://azure.github.io/azureml-web)

AMLv2 is under active development and soon entering a limited preview. It fundamentally shifts AML primarily being a Python SDK with an Azure backend to a complete and robust Azure service. We will also open source (i.e. host publicly on GitHub) as much of the product and accompanying assets as possible.

These "new" repos (with slight exception of some of the website content) are fully aligned with AMLv2. 

So the short answer is, if you're just getting started with AML and want the smoothest possible transition, follow the best practices and guidance in the "new" repos. If you run into something you can't do, open an issue and we can likely guide you the most correct way to do things going forward.

If you're already using AML, you can use these repos as reference for best practices which will be recommended going forward.

Regardless, you should still refer to docs.microsoft.com/azure/machine-learning as the official product documentation. We are using the website to more rapidly iterate on curated content (particularly with our data science team), with the intention of it being promoted to docs.microsoft.com. Expect the official documentation to eventually align with these new repos over time.

We will replace Azure/MachineLearningNotebooks with Azure/azureml-examples, but this will take some time. Follow the new repo for best practices which will carry forward into v2. Refer to the old for AutoML/Pipelines notebooks.

You can think of Azure/azureml-template as an evolution of MLOps (from the same PM team), built entirely on GitHub actions. The old MLOps repos are still a great source of content. We will do a backfill of existing template/accelerator repositories to fit into the new template structure, which will be indexed on the website and promoted to official docs.

## Long answer

Unfortunately, that was the short answer. I'm going to write up and publicly post the long answer for reference. Feel free to stop reading.

### AML"v1"

AML as it is today -- https://docs.microsoft.com/en-us/azure/machine-learning/ -- became generally available ~2 years ago. It primarily consists of a Python SDK backed by REST APIs, with a limited CLI. Over time, the SDK has changed a lot. There have been a number of blatant breaking changes, shifts in direction for major features, and a lot of client-side implementation. While there is a lot of functionality in the Python SDK, other surface areas suffered - the CLI, the R SDK (built on top of the Python SDK), and our backend APIs.

There has been feature creep, and too many ways to accomplish the same thing. 

We have `DataReference` and `PipelineData` and `DataPath` and `Dataset` (the original) and `Dataset.Tabular` and `Dataset.File` and...

We have `Estimator` and `ScriptRunConfig` and `CommandJob` (coming soon!) and `EstimatorStep` and `AutoMLStep` and `ScriptRunStep` and ... 

In Pipelines, we have a DataBricks step with no corresponding single job submission. We have a completely different HDInsights and Synapse step (coming soon!). We have ML Pipelines, Azure DevOps Pipelines, Azure Data Factory Pipelines, Synapse Pipelines...

We used to recommend using the `Image` class, now we recommend `Environment`. Many key features ended up in `contrib` packages, which rarely made it into the main SDK. The list of issues goes on.

**This is not to say AMLv1 is bad or unusable.** On the contrary, Microsoft is recognized as a leader in the ML space and many large enterprises, including Microsoft organizations, run their production workloads on AMLv1. Used correctly, it is a powerful and productive tool for automating the entire ML lifecycle and scaling up/out on Azure compute, with central tracking. We have learned an incredible amount from our users in the past years, and look forward to implementing those learnings in v2 to deliver *the best ML cloud tool.*

### docs.microsoft.docs and Azure/MachineLearningNotebooks

With our documentation and examples, there are five major issues:

1. focus on AML product, not user's job to be done
2. using Jupyter notebooks for everything
3. using Python for everything
4. no separation between job configuration and user (ML) code
5. no strategy for GitHub repos

These new assets aim to address this issues and align with AMLv2. Most of this will make its way into docs.microsoft.com.

Our official documentation and examples are reflective of the issues in AMLv1. They focus in many places on teaching ML, which is not the AML team's focus. They focus on how to use the AML feature, not how to get the user's job done. They flagrantly mix AML control plane code with ML code. 

Expect the tutorials and samples sections on docs to closely align with the new repos in the near future. Expect the how-to guides to slowly align with the new repos and AMLv2. Expect the concepts to change abruptly for AMLv2.

### AMLv2

"The 2.0 developer platform provides first class API / CLI / SDK support for model training and scoring scenarios." It is entering a closed preview this month. A variety of SDKs will be auto-generated from the base APIs. A curated CLI and Python SDK will be built. 

The number of concepts will be reduced. All assets (including jobs) will be Azure Resource Manager (ARM) resources, which has numerous beneficial implications.

Everything you can do in v1 you will be able to do in v2, but a lot will change. We want to begin aligning with that change now with the new repos.

### New repos

This brings us to the new repositories, specifically:

- Azure/azureml-examples
- Azure/azureml-template
- Azure/azureml-web

I was assigned to reorganize and cleanup our existing example repository, Azure/MachineLearningNotebooks, and help with our docs for v2. The following issues exist in our existing documentation and examples:

- no clear separation between documentation and examples
  - refer to each other throughout
  - some critical content only available in Jupyter notebooks
- focus on how to use AML, not how to get a job done
- too many concepts, ways to do things
- too much semi-supported stuff
- using Jupyter notebooks for everything
- using Python for everything
- examples incredibly difficult to contribute to 
  - impossible for non-AML team members
  - incredibly painful for AML team members
  - takes weeks to roll out updates

The examples specifically:

- were inconsistent and duplicative (`train-with-deep-learning`, `ml-frameworks`, and `training` were all directories)
- many documents outdated 
- about 50% of links broken
- 140+ issues not responded to 
- issues frequently contain broken promises
- 70+ stale PRs, many on content that no longer exists with no comments
- convoluted editing and testing process in internal Azure DevOps repo
- somewhat used by engineering for integration testing, rather than being user-facing content

I tried to get people onboard with and implement a plan to overhaul Azure/MachineLearningNotebooks, and I failed. We took it as an opportunity to start over with our examples, hosted on GitHub, following AMLv2 best practices, renaming to remove focus on Notebooks, and provide a meaningful set of user-facing examples which the community (including internally at Microsoft, outside of AML) can contribute to.

So, Azure/azureml-examples began. You can see the [contributing guidelines](https://github.com/Azure/azureml-examples/blob/main/CONTRIBUTING.md) for the general philosophy, which in short requires:

- consistent organization
- consistent naming
- separation of job configuration and ML code
- using an opinionated (i.e. AMLv2-aligned) subset of AML
- hosting on GitHub
- testing through GitHub actions
- using the most correct tool for the job
- focus on user-centric job to be done

The goal is absolutely to replace Azure/MachineLearningNotebooks. 

In parallel to this effort, the AML Data Science (DS) team published a [Cheat Sheet](https://azure.github.io/azureml-web/docs/cheatsheet/). Other Azure products, and most data science tools, have a cheat sheet. While we'll eventually host it officially on docs.microsoft.com, GitHub gives us a great way to quickly iterate on content. So, you can consider the website a complementary guide with a reduced set of documentation curated by the DS and PM team which is largely aligned with v2. 

We hosted the cheatsheet on Azure/azureml-examples, but over time felt it would be beneficial to separate into its own repo, where it now lives. The goal of this is not to replace docs.microsoft.com, but rather host less-official (but hopefully very useful) content we can rapidly iterate on with the intention of eventually promoting to official documentation.

Additionally, it became clear we needed a slimmed down template, so Azure/azureml-template was created. The template is based off learnings from the examples, which initially followed https://github.com/dslp/dslp but diverged significantly (for reasons I'll write up in an issue there soon-ish). We have a number of semi-official repos on GitHub, many poorly maintained. The intent here is to create a clear system for adding framework and scenario-specific templates, hosted on GitHub and automated through GitHub actions. For future proofing, these templates should align with AMLv2. We will have a backfill effort to conform existing repos to the template structure, and re-publish them. They must be comprehensively tested and conform to best practices for easy migration to v2.

We have a lot of Microsoft internal teams, outside of the AML engineering team, looking to contribute but lacking the process to do so effectively. This is an attempt to document and release that process.

### Open Source

Microsoft <3 Open Source. AML <3 Open Source, but we don't do a great job showing it. Outside of the main documentation (i.e. not including SDK docs), nothing in AML is open source or publicly hosted. These leads to a few issues:

- fragmented experience for internal and external users 
- lack of accountability 
- lack of transparency
- various others

AMLv2, and starting now, everything we can will be hosted on GitHub. This includes all the new repos, will include the various SDKs and corresponding docs, and (hopefully) will lead to better responsiveness from the team on GitHub. 

For transparency, this means we can clearly document our contributing guidelines, everyone can see the revision history, issues are not disjointed from the source, and we can do things like publish our [soon to be implemented GitHub issue triage process](https://azure.github.io/azureml-web/docs/issues). 

We no longer need to separately answer internal and external queries, as we can direct everyone to public sites for all to benefit from. We can easily reference the published content, like this issue (which I will definitely reference going forward).

### Conclusion

AMLv1 is great, and AMLv2 will be the best tool for accelerating and automating the entire ML lifecycle, for single users to multi-disciplinary teams in large enterprises. 

We do understand the confusion and friction this causes. Per the short answer, if you are new I'd suggest sticking to the new examples, template, and website where possible, referring to docs.microsoft.com if necessary for additional content.

I hope you find this answer helpful.

**Comment by kodonnell** [comment]
>I hope you find this answer helpful.

Wow, that's was fantastic Cody! 

Firstly, it was good to hear you own some of the downsides of AMLv1 - we've done our best to love it and sell it to customers, but AMLv1's made it pretty hard, for some of the reasons you mention.

Secondly, AMLv2 sounds great. I might reach out around the preview.

In the interests of not polluting this thread, I'm not keen to make too many suggestions about things I don't have enough context on. The main one for me is actually "AMLv2". AML has meant many things before - there was Studio, then Workbench, then currently AML (Services? Still not sure!) which also had some Studio in it, and AML AutoML etc., and now this which may or may not appear as a big change to customers. This was a bit problematic for us, because a) general confusion, but especially b) Googling for docs/issues/etc. was pretty confusing for a while, with so many irrelevant matches. So a different name may have some positive aspects (though I'm not sure it'd outweigh the negative) - and I mention it here, as it seems to align with some of the general objectives of improve docs/examples/community/etc. That said, I suspect you're well across that anyway, in which case, no need to reply.

Feel free to close if you wish, or leave this open if you're wanting any other feedback like the above.

**Comment by lostmygithubaccount** [comment]
I think we should leave this issue open until it is fixed (i.e. clear in our documentation). 

> Firstly, it was good to hear you own some of the downsides of AMLv1 - we've done our best to love it and sell it to customers, but AMLv1's made it pretty hard, for some of the reasons you mention.

The team is very aware of the downside, and hopefully all will be fixed with AMLv2 and stable APIs there.

> In the interests of not polluting this thread, I'm not keen to make too many suggestions about things I don't have enough context on. The main one for me is actually "AMLv2". AML has meant many things before - there was Studio, then Workbench, then currently AML (Services? Still not sure!) which also had some Studio in it, and AML AutoML etc., and now this which may or may not appear as a big change to customers. This was a bit problematic for us, because a) general confusion, but especially b) Googling for docs/issues/etc. was pretty confusing for a while, with so many irrelevant matches. So a different name may have some positive aspects (though I'm not sure it'd outweigh the negative) - and I mention it here, as it seems to align with some of the general objectives of improve docs/examples/community/etc. That said, I suspect you're well across that anyway, in which case, no need to reply.

I think we're technically on v5 or v6! We are aware of the docs issues, but I'll bring it up with the team again - I would not expect a name change for the product.

**Comment by jpe316** [comment]
Thanks for the feedback! We're in the process of cleaning up all of the documentation and samples. The 2.0 release of our SDK / CLI / API experiences should help make your life easier, but there are no disruptive changes to the service itself. Stay tuned :)

**Comment by arnabbiswas1** [comment]
In my project, we are exploring AzureML for sometime and started actively using it recently. Pipelines are being built, codes are being composed. During the process, **how will I know if an existing API is going to be deprecated in AMLv2**? 

Just for an example, `PipelineData` vs `OutputFileDatasetConfig`. The current [documentation ](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-your-first-pipeline#set-up-machine-learning-resources) gives an impression that `OutputFileDatasetConfig` is the way to go, but now with v2, things may change?

I understand the thumb rule from Cody's answer:

> if you are new I'd suggest sticking to the new examples, template, and website where possible, referring to docs.microsoft.com if necessary for additional content.

**Is there any other suggestion, so that as a developer we don't write code which will be obsolete very soon.**

Also, **Is there any (very) rough timeline for AMLv2 preview and GA?**

Best wishes for the work you are doing & ❤️ to Microsoft.

**Comment by jpe316** [comment]
Existing APIs will not be immediately deprecated -SDK contracts are going to change but your existing workloads won’t stop running all of a sudden. You will notice in-place updates to contracts and depreciations (such as ScriptRunConfig improvements and Estimator deprecation) which are aligning our current experience towards the 2.0 contract.

Pipelines is a specific area we’re looking to clean up and simplify. We’d love your feedback!

@MayMSFT can comment on PipelineData - in general, we would recommend that you use datasets.

**Comment by arnabbiswas1** [comment]
> @MayMSFT can comment on PipelineData - in general, we would recommend that you use datasets.

Do you mean you are recommending `OutputFileDatasetConfig` over `PipelineData `? Please let me know.

**Comment by lostmygithubaccount** [comment]
That is the recommendation - use `Dataset` for everything. We will be doing some cleanup of the documentation and examples (similar to recent removal of `Estimator`)
